source 'https://rubygems.org'
ruby '2.3.0'

gem 'autoprefixer-rails'
gem 'font-awesome-sass'
gem 'jekyll'
gem 'jekyll-assets'
gem 'jekyll-sitemap'
gem 'kramdown'
gem 'puma'
gem 'rack-jekyll'
gem 'rake'
gem 'sprockets-es6'
